# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
          - name: Repository Traffic
  # You may pin to the exact commit or the version.
  # uses: sangonzal/repository-traffic-action@f2be5556d64beb6c5ae47878944787aeb6f39ba6
  uses: sangonzal/repository-traffic-action@v0.1.4
  with:
    # 
    branch: # optional, default is dev
    
    
    
- name: Traffic to Badge
  # You may pin to the exact commit or the version.
  # uses: yi-Xu-0100/traffic-to-badge@6e7656202ad370afe7e80465c32ee367324ab4fc
  uses: yi-Xu-0100/traffic-to-badge@v1.4.0
  with:
    # Set up a personal access token to obtain the secret repository traffic data.

    my_token: 
    # Set up a list of repositories to get. Only when github.repository with setting into first item, it can be correct to be current repository name.

    static_list: # optional, default is ${{ github.repository }}
    # If empty traffic data will be backed up to the branch named traffic.

    traffic_branch: # optional, default is traffic
    # Set a hex or named color value for the views badge background.

    views_color: # optional, default is brightgreen
    # Set a hex or named color value for the clones badge background.

    clones_color: # optional, default is brightgreen
    # Set a hex or named color value for the views per week badge background.

    views_week_color: # optional, default is brightgreen
    # Set a hex or named color value for the clones per week badge background.

    clones_week_color: # optional, default is brightgreen
    # Set a hex or named color value for the total views badge background.

    total_views_color: # optional, default is brightgreen
    # Set a hex or named color value for the total clones badge background.

    total_clones_color: # optional, default is brightgreen
    # Set a hex or named color value for the total views per week badge background.

    total_views_week_color: # optional, default is brightgreen
    # Set a hex or named color value for the total clones per week badge background.

    total_clones_week_color: # optional, default is brightgreen
    # Insert a named logo or simple-icon to the left of the label.

    logo: # optional, default is github
    # Set a year number for license year beginning. If empty, it will no beginning year.

    year: # optional
